version: '3.8'

services:
  postgres-db:
    image: postgres:14.2
    container_name: 'postgres_currency'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:54327"

  consul:
    container_name: currency_consul
    image: consul:1.11.3
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - "127.0.0.1:8000:8000"
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO

  currency-app:
    image: cbu-currency:0.0.1
    build: ./
    container_name: 'currency-app'
    ports:
        - "8080:8080"
    depends_on:
      - postgres-db

volumes:
  db:
    driver: local